version: '3'
services:
 # The Application
  prod-app:
    image: mom21islove/prod-app
    working_dir: /var/www
    container_name: prod-app
    volumes:
      - /var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=prod-db"
    networks:
      - app-network 
#The Web Server
  web:
    image: mom21islove/prod-web
    ports:
      - 9881:80
      - 748:443
    container_name: prod-web
    networks:
      - app-network 
#The Database
  prod-db:
    image: mysql:5.7.22
    container_name: prod-db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    networks:
      - app-network 
#Docker Networks
networks:
  app-network:
    driver: bridge
#Docker Volumes
volumes:
  dbdata:
